name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Build
      run: echo "Build Successful ✅"

    - name: Test
      run: echo "Tests Passed ✅"

    - name: Deploy
      run: echo "Deployment Done 🚀"
